### ISSUE TITLE
adobe lightroom 12.3 注入之后还会有购买弹窗，点击关闭窗口进程自动退出

### ISSUE THREAD

**Issue by odison** [QiuChenlyOpenSource/InjectLib#21]
注入之后还会出现弹窗，点击关闭窗口进程自动退出了。

附：

[🔔] 此App包不是常见类型结构，请注意当前App注入的路径是 /Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app
[🤔] [Adobe Lightroom Classic] - [12.3] - [com.adobe.LightroomClassicCC7]是受支持的版本，是否需要注入？y/n(默认n)
y
开始注入App: com.adobe.LightroomClassicCC7
备份的注入文件已经存在,需要直接用这个文件注入吗？y/n(默认y)
n

====================
2023.2.26 秋城落叶修改版
感谢insert_dylib的开源人员！仓库地址：https://github.com/Tyilo/insert_dylib
====================

/Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app/Contents/Frameworks/AdobeAGM.framework/Versions/A/AdobeAGM 目标文件已经存在. 要重写他吗? [y/n] y
这是一个FAT格式二进制,携带 2 个架构的代码(Intel/Apple Silicon ARM64).
Binary already contains a load command for that dylib. Continue anyway? [y/n] y
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
Binary already contains a load command for that dylib. Continue anyway? [y/n] y
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
添加 LC_LOAD_DYLIB 指令到通用架构, 应用程序：/Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app/Contents/Frameworks/AdobeAGM.framework/Versions/A/AdobeAGM。

**Comment by QiuChenly** [comment]
already fix it。check and reporting.

**Comment by odison** [comment]
12.4 可以用了。
另外请教下，arm64跟intel的 需要hook的函数基址是一样的么？

**Comment by odison** [comment]
[macOS-InjectPluginCode](https://github.com/QiuChenlyOpenSource/macOS-InjectPluginCode)   这个仓库能更新下么？

**Comment by odison** [comment]
我ida分析了 adobe的app  发现  arm64 跟 intel 基址有区别

**Comment by digitalhouse** [comment]
> 12.4 可以用了。 另外請教下，arm64跟intel的 需要hook的函數基址是一樣的麼？

12.4可以用了？ 我的怎麼打開編輯照片都是灰的？

**Comment by odison** [comment]
> 

sorry，我只试了打开进程没关闭，确实编辑都是不可用

**Comment by ntpd1** [comment]
[🔔] 此App包不是常见类型结构，请注意当前App注入的路径是 /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app
[🔔] This App Folder is not common struct,pls attention now inject into the app path is /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app
[🤔] [Adobe Photoshop 2023] - [24.7.0] - [com.adobe.Photoshop]是受支持的版本，是否需要注入？y/n(默认n)
y
开始注入App: com.adobe.Photoshop
备份的原始文件已经存在,需要直接用这个文件注入吗？y/n(默认y)
Find Previous Target File Backup, Are u use it inject？y/n(default is y)
y


====================
2023.2.26 秋城落叶修改版
感谢insert_dylib的开源人员！仓库地址：https://github.com/Tyilo/insert_dylib
====================

/Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/Frameworks/AdobeAGM.framework/Versions/A/AdobeAGM 目标文件已经存在. 要重写他吗? [y/n] y
这是一个FAT格式二进制,携带 1 个架构的代码(Intel/Apple Silicon ARM64).
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
添加 LC_LOAD_DYLIB 指令到通用架构, 应用程序：/Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/Frameworks/AdobeAGM.framework/Versions/A/AdobeAGM。

ps beta版本破解后打开闪退

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Adobe Photoshop 2023 [17643]
Path:                  /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/MacOS/Adobe Photoshop 2023
Identifier:            com.adobe.Photoshop
Version:               24.7.0 (24.7.0)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-06-24 23:47:02.1857 +0800
OS Version:            macOS 12.6.6 (21G646)
Report Version:        12
Anonymous UUID:        4BB15398-99D4-A074-9985-D4769080BB59

Sleep/Wake UUID:       9B527B26-B820-4903-A30B-C5E0581EF995

Time Awake Since Boot: 70000 seconds
Time Since Wake:       11753 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_GUARD (SIGKILL)
Exception Codes:       GUARD_TYPE_VIRT_MEMORY
Exception Codes:       0x0000000000000000, 0x0000000114876000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace GUARD, Code 11529215050363437056 

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff8029d3466 __mmap + 10
1   libsystem_kernel.dylib        	    0x7ff8029d33fd mmap + 48
2   libInjectLib.dylib            	       0x117b767e6 OSMemory::Allocate(unsigned long, MemoryPermission, void*) + 70
3   libInjectLib.dylib            	       0x117b76e69 NearMemoryAllocator::allocateNearBlockFromUnusedRegion(unsigned int, unsigned long, unsigned long, bool) + 249
4   libInjectLib.dylib            	       0x117b7724c NearMemoryAllocator::allocateNearDataMemory(unsigned int, unsigned long, unsigned long) + 204
5   libInjectLib.dylib            	       0x117b745f2 GenerateNormalTrampolineBuffer(unsigned long, unsigned long) + 114
6   libInjectLib.dylib            	       0x117b744f3 InterceptRouting::GenerateTrampolineBuffer(unsigned long, unsigned long) + 67
7   libInjectLib.dylib            	       0x117b747ae FunctionInlineHookRouting::DispatchRouting() + 30
8   libInjectLib.dylib            	       0x117b74734 DobbyHook + 164
9   libInjectLib.dylib            	       0x117b70a91 hookPtr + 62
10  libInjectLib.dylib            	       0x117b6fc1d AdobeApps + 133
11  libInjectLib.dylib            	       0x117b70986 +[InjectLib load] + 54
12  libobjc.A.dylib               	    0x7ff8028a5b6f load_images + 1319
13  dyld                          	       0x11a4c4334 dyld4::RuntimeState::notifyObjCInit(dyld4::Loader const*) + 170
14  dyld                          	       0x11a4c9f03 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 167
15  dyld                          	       0x11a4c9ef1 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 149
16  dyld                          	       0x11a4c9ef1 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 149
17  dyld                          	       0x11a4c9fb2 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 108
18  dyld                          	       0x11a4dd826 dyld4::APIs::runAllInitializersForMain() + 222
19  dyld                          	       0x11a4bb38d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3443
20  dyld                          	       0x11a4ba4e4 start + 388

Thread 1:
0   libsystem_pthread.dylib       	    0x7ff802a0af48 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	    0x7ff802a0af48 start_wqthread + 0


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000114876000  rbx: 0x00000000ff000000  rcx: 0x00007ff7b4dfb7e8  rdx: 0x0000000000000000
  rdi: 0x0000000114876000  rsi: 0x0000000000001000  rbp: 0x00007ff7b4dfb810  rsp: 0x00007ff7b4dfb7e8
   r8: 0x00000000ff000000   r9: 0x0000000000000000  r10: 0x0000000000041012  r11: 0x0000000000000206
  r12: 0x0000000000001012  r13: 0x0000000114876000  r14: 0x0000000000001000  r15: 0x0000000114876000
  rip: 0x00007ff8029d3466  rfl: 0x0000000000000206  cr2: 0x00007fb70f01a010
  
Logical CPU:     0
Error Code:      0x020000c5 
Trap Number:     133


Binary Images:
    0x7ff8029d1000 -     0x7ff802a08fff libsystem_kernel.dylib (*) <35a199f3-e389-3202-916b-d6662a391f7e> /usr/lib/system/libsystem_kernel.dylib
       0x117b6b000 -        0x117b7afff libInjectLib.dylib (*) <f2f0c8b1-9f3f-3313-b33f-2222013f553d> /Users/USER/Downloads/*/libInjectLib.dylib
    0x7ff80289c000 -     0x7ff8028d5fff libobjc.A.dylib (*) <4d9b0dca-7151-3875-b98e-b255db8267a8> /usr/lib/libobjc.A.dylib
       0x11a4b5000 -        0x11a520fff dyld (*) <2517e9fe-884a-3855-8532-92bffba3f81c> /usr/lib/dyld
    0x7ff802a09000 -     0x7ff802a14fff libsystem_pthread.dylib (*) <e5d44afd-2577-3cee-8711-9d8d426229e0> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

**Comment by digitalhouse** [comment]
> [🔔] 此App包不是常見類型結構，請注意當前App注入的路徑是 /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app [🔔] This App Folder is not common struct,pls attention now inject into the app path is /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app [🤔] [Adobe Photoshop 2023] - [24.7.0] - [com.adobe.Photoshop]是受支援的版本，是否需要注入？y/n(默認n) y 開始注入App: com.adobe.Photoshop 備份的原始檔案已經存在,需要直接用這個檔案注入嗎？y/n(默認y) Find Previous Target File Backup, Are u use it inject？y/n(default is y) y
> 
> # ====================
> 2023.2.26 秋城落葉修改版
> 感謝insert_dylib的開源人員！倉庫地址：https://github.com/Tyilo/insert_dylib
> /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/Frameworks/AdobeAGM.framework/Versions/A/AdobeAGM 目標檔案已經存在. 要重寫他嗎? [y/n] y 這是一個FAT格式二進制,攜帶 1 個架構的程式碼(Intel/Apple Silicon ARM64). 發現程式碼載入簽名: LC_CODE_SIGNATURE load command. 要自動刪掉嗎? [y/n] y 新增 LC_LOAD_DYLIB 指令到通用架構, 應用程式：/Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/Frameworks/AdobeAGM.framework/Versions/A/AdobeAGM。
> 
> ps beta版本破解後打開閃退
> 
> ## Translated Report (Full Report Below)
> Process: Adobe Photoshop 2023 [17643] Path: /Applications/Adobe Photoshop (Beta)/Adobe Photoshop (Beta).app/Contents/MacOS/Adobe Photoshop 2023 Identifier: com.adobe.Photoshop Version: 24.7.0 (24.7.0) Code Type: X86-64 (Native) Parent Process: launchd [1] User ID: 501
> 
> Date/Time: 2023-06-24 23:47:02.1857 +0800 OS Version: macOS 12.6.6 (21G646) Report Version: 12 Anonymous UUID: 4BB15398-99D4-A074-9985-D4769080BB59
> 
> Sleep/Wake UUID: 9B527B26-B820-4903-A30B-C5E0581EF995
> 
> Time Awake Since Boot: 70000 seconds Time Since Wake: 11753 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread: 0 Dispatch queue: com.apple.main-thread
> 
> Exception Type: EXC_GUARD (SIGKILL) Exception Codes: GUARD_TYPE_VIRT_MEMORY Exception Codes: 0x0000000000000000, 0x0000000114876000 Exception Note: EXC_CORPSE_NOTIFY
> 
> Termination Reason: Namespace GUARD, Code 11529215050363437056
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread 0 libsystem_kernel.dylib 0x7ff8029d3466 __mmap + 10 1 libsystem_kernel.dylib 0x7ff8029d33fd mmap + 48 2 libInjectLib.dylib 0x117b767e6 OSMemory::Allocate(unsigned long, MemoryPermission, void*) + 70 3 libInjectLib.dylib 0x117b76e69 NearMemoryAllocator::allocateNearBlockFromUnusedRegion(unsigned int, unsigned long, unsigned long, bool) + 249 4 libInjectLib.dylib 0x117b7724c NearMemoryAllocator::allocateNearDataMemory(unsigned int, unsigned long, unsigned long) + 204 5 libInjectLib.dylib 0x117b745f2 GenerateNormalTrampolineBuffer(unsigned long, unsigned long) + 114 6 libInjectLib.dylib 0x117b744f3 InterceptRouting::GenerateTrampolineBuffer(unsigned long, unsigned long) + 67 7 libInjectLib.dylib 0x117b747ae FunctionInlineHookRouting::DispatchRouting() + 30 8 libInjectLib.dylib 0x117b74734 DobbyHook + 164 9 libInjectLib.dylib 0x117b70a91 hookPtr + 62 10 libInjectLib.dylib 0x117b6fc1d AdobeApps + 133 11 libInjectLib.dylib 0x117b70986 +[InjectLib load] + 54 12 libobjc.A.dylib 0x7ff8028a5b6f load_images + 1319 13 dyld 0x11a4c4334 dyld4::RuntimeState::notifyObjCInit(dyld4::Loader const*) + 170 14 dyld 0x11a4c9f03 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 167 15 dyld 0x11a4c9ef1 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 149 16 dyld 0x11a4c9ef1 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 149 17 dyld 0x11a4c9fb2 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 108 18 dyld 0x11a4dd826 dyld4::APIs::runAllInitializersForMain() + 222 19 dyld 0x11a4bb38d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3443 20 dyld 0x11a4ba4e4 start + 388
> 
> Thread 1: 0 libsystem_pthread.dylib 0x7ff802a0af48 start_wqthread + 0
> 
> Thread 2: 0 libsystem_pthread.dylib 0x7ff802a0af48 start_wqthread + 0
> 
> Thread 0 crashed with X86 Thread State (64-bit): rax: 0x0000000114876000 rbx: 0x00000000ff000000 rcx: 0x00007ff7b4dfb7e8 rdx: 0x0000000000000000 rdi: 0x0000000114876000 rsi: 0x0000000000001000 rbp: 0x00007ff7b4dfb810 rsp: 0x00007ff7b4dfb7e8 r8: 0x00000000ff000000 r9: 0x0000000000000000 r10: 0x0000000000041012 r11: 0x0000000000000206 r12: 0x0000000000001012 r13: 0x0000000114876000 r14: 0x0000000000001000 r15: 0x0000000114876000 rip: 0x00007ff8029d3466 rfl: 0x0000000000000206 cr2: 0x00007fb70f01a010
> 
> Logical CPU: 0 Error Code: 0x020000c5 Trap Number: 133
> 
> Binary Images: 0x7ff8029d1000 - 0x7ff802a08fff libsystem_kernel.dylib (_) <35a199f3-e389-3202-916b-d6662a391f7e> /usr/lib/system/libsystem_kernel.dylib 0x117b6b000 - 0x117b7afff libInjectLib.dylib (_) /Users/USER/Downloads/_/libInjectLib.dylib 0x7ff80289c000 - 0x7ff8028d5fff libobjc.A.dylib (_) <4d9b0dca-7151-3875-b98e-b255db8267a8> /usr/lib/libobjc.A.dylib 0x11a4b5000 - 0x11a520fff dyld (_) <2517e9fe-884a-3855-8532-92bffba3f81c> /usr/lib/dyld 0x7ff802a09000 - 0x7ff802a14fff libsystem_pthread.dylib (_) /usr/lib/system/libsystem_pthread.dylib
> 
> External Modification Summary: Calls made by other processes targeting this process: task_for_pid: 0 thread_create: 0 thread_set_state: 0 Calls made by this process: task_for_pid: 0 thread_create: 0 thread_set_state: 0 Calls made by all processes on this machine: task_for_pid: 0 thread_create: 0 thread_set_state: 0

又一個SB

**Comment by digitalhouse** [comment]
已在其他地方找到M晶片用的LR 12.4破解，並可正常使用

**Comment by QiuChenly** [comment]
编辑无法使用的问题还在研究中，后续可能会更新。

**Comment by QiuChenly** [comment]
> 已在其他地方找到M晶片用的LR 12.4破解，並可正常使用

我看了很久Lrc，你是怎么正常使用的？我这里暗转SIce的版本后依然还是编辑功能灰色，我不知道是什么原因引起的。是不是我账户没有试用过？

**Comment by digitalhouse** [comment]
> > 已在其他地方找到M晶片用的LR 12.4破解，並可正常使用
> 
> 我看了很久Lrc，你是怎麼正常使用的？我這裡安裝SIce的版本後依然還是編輯功能灰色，我不知道是什麼原因引起的。是不是我帳戶沒有試用過？

我在其他地方有找到M晶片LRC 12.5可以用的破解

**Comment by QiuChenly** [comment]
问题已解决。
