### ISSUE TITLE
PS 25.0 arm版本

### ISSUE THREAD

**Issue by digitalhouse** [QiuChenlyOpenSource/InjectLib#87]
PS 25.0 arm版本打開依然彈出購買視窗
無法使用
現在是arm已經都不破解了嗎？

**Comment by QiuChenly** [comment]
没有人提供ARM版本文件。。。并且130MB+的文件IDA跑的很慢 ARM汇编特征码寻找起来也很费劲

**Comment by digitalhouse** [comment]
> 沒有人提供ARM版本檔案。。。並且130MB+的檔案IDA跑的很慢 ARM彙編特徵碼尋找起來也很費勁

原來是這樣 文件的部分我是可以幫忙提供

**Comment by digitalhouse** [comment]
> 沒有人提供ARM版本檔案。。。並且130MB+的檔案IDA跑的很慢 ARM彙編特徵碼尋找起來也很費勁

https://mega.nz/folder/DIIjALaD#42tMEukqLYhJbwyYPgmNgA

**Comment by QiuChenly** [comment]
稍晚些时候上传新的ARM补丁
 他的版本是？

**Comment by digitalhouse** [comment]
> 稍晚些時候上傳新的ARM補丁 他的版本是？

https://mega.nz/folder/3RIj2LBI#823ntUDH4G7EqGWaCq2d5w
一個24.7.1 PS2023版的
一個25.0 PS2023版的

**Comment by QiuChenly** [comment]
可是PS稳定版已经发布25.0了啊

**Comment by digitalhouse** [comment]
> 可是PS穩定版已經發佈25.0了啊

應該是2023跟2024的區別

**Comment by QiuChenly** [comment]
2023的我已经在代码中删掉了  现在是按照2024来的

**Comment by QiuChenly** [comment]
晚上我看看arm版本的特征码更新上来

**Comment by QiuChenly** [comment]
主要是ida分析arm数据量太大了 要等将近一个小时

**Comment by QiuChenly** [comment]
hey can u test Adobe PS / PS Beta lasted FOR ARM64 Mac tomorrow? i will upload patch code to github later.

**Comment by digitalhouse** [comment]
> hey can u test Adobe PS / PS Beta lasted FOR ARM64 Mac tomorrow? i will upload patch code to github later.

ok

**Comment by QiuChenly** [comment]
你在我的tg群里吗？

**Comment by digitalhouse** [comment]
> 你在我的tg群里吗？ 也许你可以join it

沒有耶 可以私訊給我加入？

**Comment by QiuChenly** [comment]
在我的readme最下部有加群链接

**Comment by gkl1368** [comment]
实测只能使用intel模式打开 ps25.0正式版和25.1 测试版 用arm模式开 都提示开始试用

**Comment by digitalhouse** [comment]
終於成功用上arm版PS 2024 25.0了
<img width="1726" alt="截圖 2023-09-18 20 51 22" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/786348/ee537a72-caf3-4614-9078-46c2a2a50ff0">

**Comment by gkl1368** [comment]
> 終於成功用上arm版PS 2024 25.0了
> 
> <img width="1726" alt="截圖 2023-09-18 20 51 22" src="https://github.com/QiuChenlyOpenSource/InjectLib/assets/786348/ee537a72-caf3-4614-9078-46c2a2a50ff0">
> 
> 

为什么我这里不行

**Comment by Solmonz** [comment]
报错 
M1 芯片
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Adobe Photoshop 2024 [2143]
Path:                  /Applications/Adobe Photoshop 2024/Adobe Photoshop 2024.app/Contents/MacOS/Adobe Photoshop 2024
Identifier:            com.adobe.Photoshop
Version:               25.0.0 (25.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-18 22:23:26.4327 +0800
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        ******************
Sleep/Wake UUID:       ******************
Time Awake Since Boot: 2900 seconds
Time Since Wake:       695 seconds

System Integrity Protection: enabled

Crashed Thread:        17  com.adobe.ngl-0x16e7b7000

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000003201f08

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [2143]

Thread 0:: Main Thread 25.0.0 20230906.r.37 b14e317 Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1a5737f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1a574a280 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1a5740bb8 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x1a57382d0 mach_msg + 24
4   CoreFoundation                	       0x1a58567e4 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1a58550c4 __CFRunLoopRun + 1208
6   CoreFoundation                	       0x1a58544b8 CFRunLoopRunSpecific + 612
7   HIToolbox                     	       0x1af0a6df0 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x1af0a6c2c ReceiveNextEventCommon + 648
9   HIToolbox                     	       0x1af0a6984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x1a8a7b97c _DPSNextEvent + 636
11  AppKit                        	       0x1a8a7ab18 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
12  Adobe Photoshop 2024          	       0x1052aeb00 0x10201c000 + 53029632
13  AppKit                        	       0x1a8a6ef7c -[NSApplication run] + 464
14  Adobe Photoshop 2024          	       0x1052afe50 0x10201c000 + 53034576
15  Adobe Photoshop 2024          	       0x1052b21b8 0x10201c000 + 53043640
16  Adobe Photoshop 2024          	       0x105308400 0x10201c000 + 53396480
17  Adobe Photoshop 2024          	       0x1067fef34 0x10201c000 + 75378484
18  Adobe Photoshop 2024          	       0x10201f5f0 0x10201c000 + 13808
19  dyld                          	       0x1a541ff28 start + 2236

Thread 1:
0   libsystem_pthread.dylib       	       0x1a5772d8c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1a5772d8c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1a5772d8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1a5772d8c start_wqthread + 0

Thread 5:: HB Kill Signal Processor
0   libsystem_kernel.dylib        	       0x1a573e0a0 kevent + 8
1   Adobe Photoshop 2024          	       0x1067fc764 0x10201c000 + 75368292
2   Adobe Photoshop 2024          	       0x1067fca64 0x10201c000 + 75369060
3   libsystem_pthread.dylib       	       0x1a5777fa8 _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1a5772da0 thread_start + 8

Thread 6:: com.adobe.ngl-RecurringSync-0x16e127000
0   libsystem_kernel.dylib        	       0x1a5737f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1a574a280 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x1a5740bb8 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x1a57382d0 mach_msg + 24
4   libdispatch.dylib             	       0x1a55e39f8 _dispatch_mach_send_and_wait_for_reply + 548
5   libdispatch.dylib             	       0x1a55e3d88 dispatch_mach_send_with_result_and_wait_for_reply + 60
6   libxpc.dylib                  	       0x1a54b9c3c xpc_connection_send_message_with_reply_sync + 264
7   Security                      	       0x1a7f8866c securityd_message_with_reply_sync + 124
8   Security                      	       0x1a7f89630 securityd_send_sync_and_do + 88
9   Security                      	       0x1a7fefa78 cftype_to_bool_cftype_error_request + 160
10  Security                      	       0x1a7ff46a4 __SecItemCopyMatching_ios_block_invoke_2 + 208
11  Security                      	       0x1a7ff18c0 __SecItemAuthDoQuery_block_invoke + 540
12  Security                      	       0x1a7ff0b00 SecItemAuthDoQuery + 1324
13  Security                      	       0x1a7ff45c8 __SecItemCopyMatching_ios_block_invoke + 140
14  Security                      	       0x1a7feea38 SecOSStatusWith + 56
15  Security

**Comment by QiuChenly** [comment]
把你报错的ps版本主程序发蓝奏云上来我看看 不要发这种没用的日志

**Comment by digitalhouse** [comment]
> > 終於成功用上arm版PS 2024 25.0了
> > <img alt="截圖 2023-09-18 20 51 22" width="1726" src="https://user-images.githubusercontent.com/786348/268649808-ee537a72-caf3-4614-9078-46c2a2a50ff0.png">
> 
> 為什麼我這裡不行

我用的是其他的破解版本

**Comment by digitalhouse** [comment]
我明天再全部上傳一次arm 64的檔案吧

**Comment by digitalhouse** [comment]
先更新上傳了pr beta跟ps beta arm64最新版的
https://mega.nz/file/qExn0RgA#-SnDc2Ftfshq6el17kdJctST9pyGKDSeRsR1QNcgujY
https://mega.nz/file/LRQkFKaR#6FzCgwD0-SQuBiHL88ujhZRiVB_ws9sV5AXIZPOf_PM

**Comment by QiuChenly** [comment]
Resolved。
